In [4]:
import pandas as pd
import numpy as np


In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [6]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

Q1. Pandas version
- > What's the version of Pandas that you installed?

In [7]:
pd.__version__

'2.1.4'

Q2. Records count
- > How many records are in the dataset?

In [9]:
df.shape[0]

2160

Q3. Laptop brands
- > How many laptop brands are presented in the dataset?

In [10]:
df['Brand'].nunique()

27

Q4. Missing values
- > How many columns in the dataset have missing values?

In [14]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Q5. Maximum final price
- > What's the maximum final price of Dell notebooks in the dataset?

In [17]:
df.loc[df['Brand'] == 'Dell', "Final Price"].max()

3936.0

Q6. Median value of Screen

- > Find the median value of Screen column in the dataset.
- > Next, calculate the most frequent value of the same Screen column.
- > Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
- > Now, calculate the median value of Screen once again.

In [18]:
# Find the median value of Screen column in the dataset.
df['Screen'].median()

15.6

In [19]:
# Next, calculate the most frequent value of the same Screen column.
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [24]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)

In [25]:
# Now, calculate the median value of Screen once again.
df['Screen'].median()

15.6

Q7. Sum of weights

- > Select all the "Innjoo" laptops from the dataset.
- > Select only columns RAM, Storage, Screen.
- > Get the underlying NumPy array. Let's call it X.
- > Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- > Compute the inverse of XTX.
- > Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
- > Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- > What's the sum of all the elements of the result?

In [27]:
# Select all the "Innjoo" laptops from the dataset
brand_innjoo = df.loc[df['Brand'] == 'Innjoo']

In [28]:
# Select only columns RAM, Storage, Screen.
brand_innjoo.loc[:, ['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [29]:
# Get the underlying NumPy array. Let's call it X
X = brand_innjoo.loc[:, ['RAM', 'Storage', 'Screen']].values

X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [31]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)

XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [33]:
# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [34]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

y

array([1100, 1300,  800,  900, 1000, 1100])

In [35]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T).dot(y)

w

array([45.58076606,  0.42783519, 45.29127938])

In [36]:
# What's the sum of all the elements of the result?
w.sum()

91.2998806299555